(function() {var implementors = {};
implementors['owning_ref'] = ["impl&lt;O, T: ?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;T&gt; for <a class='struct' href='owning_ref/struct.OwningRef.html' title='owning_ref::OwningRef'>OwningRef</a>&lt;O, T&gt;",];implementors['libc'] = [];implementors['nix'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='nix/sys/ioctl/libc/struct.sigset_t.html' title='nix::sys::ioctl::libc::sigset_t'>sigset_t</a>&gt; for <a class='struct' href='nix/sys/signal/struct.SigSet.html' title='nix::sys::signal::SigSet'>SigSet</a>",];implementors['mio'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='std::ffi::os_str::OsStr'>OsStr</a>&gt; for <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='std::path::Path'>Path</a>&gt; for <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>",];implementors['mioco'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='std::ffi::os_str::OsStr'>OsStr</a>&gt; for <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='std::path::Path'>Path</a>&gt; for <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
