(function() {var implementors = {};
implementors['coroutine'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='coroutine/coroutine_clonable/struct.Handle.html' title='coroutine::coroutine_clonable::Handle'>Handle</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='coroutine/options/struct.Options.html' title='coroutine::options::Options'>Options</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='enum' href='coroutine/enum.State.html' title='coroutine::State'>State</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='enum' href='coroutine/enum.Error.html' title='coroutine::Error'>Error</a>",];implementors['context'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='context/context/struct.Context.html' title='context::context::Context'>Context</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='context/stack/struct.Stack.html' title='context::stack::Stack'>Stack</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='context/stack/struct.StackPool.html' title='context::stack::StackPool'>StackPool</a>",];implementors['context'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='context/context/struct.Context.html' title='context::context::Context'>Context</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='context/stack/struct.Stack.html' title='context::stack::Stack'>Stack</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/thunk/core/fmt/trait.Debug.html' title='thunk::core::fmt::Debug'>Debug</a> for <a class='struct' href='context/stack/struct.StackPool.html' title='context::stack::StackPool'>StackPool</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
