(function() {var implementors = {};
implementors['owning_ref'] = ["impl&lt;O, T: ?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='owning_ref/struct.OwningRef.html' title='owning_ref::OwningRef'>OwningRef</a>&lt;O, T&gt;",];implementors['spin'] = ["impl&lt;'a, T: ?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='spin/struct.MutexGuard.html' title='spin::MutexGuard'>MutexGuard</a>&lt;'a, T&gt;","impl&lt;'rwlock, T: ?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='spin/struct.RwLockReadGuard.html' title='spin::RwLockReadGuard'>RwLockReadGuard</a>&lt;'rwlock, T&gt;","impl&lt;'rwlock, T: ?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='spin/struct.RwLockWriteGuard.html' title='spin::RwLockWriteGuard'>RwLockWriteGuard</a>&lt;'rwlock, T&gt;",];implementors['context'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='context/stack/struct.FixedSizeStack.html' title='context::stack::FixedSizeStack'>FixedSizeStack</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html' title='core::ops::Deref'>Deref</a> for <a class='struct' href='context/stack/struct.ProtectedFixedSizeStack.html' title='context::stack::ProtectedFixedSizeStack'>ProtectedFixedSizeStack</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
